- name: Stop and remove containers
  hosts: server
  become: true
  vars:
    containers:
      - influxdb
      - mosquitto
      - telegraf
  tasks:
    - name: Stop container
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ containers }}"
      ignore_errors: true
    
    - name: Remove container
      docker_container:
        name: "{{ item }}"
        state: absent
      loop: "{{ containers }}"
      ignore_errors: true
